# Changes here will be overwritten by Copier
_commit: 1.3.0-33-g5b245cb
_src_path: gh:DiamondLightSource/python-copier-template
author_email: tom.cobb@diamond.ac.uk
author_name: Tom Cobb
component_owner: group:default/sscc
description: Create an IOC from a PandA
distribution_name: pandablocks-ioc
docker: true
docs_type: sphinx
git_platform: github.com
github_org: PandABlocks
package_name: pandablocks_ioc
pypi: true
repo_name: PandABlocks-ioc
type_checker: mypy
