#!/bin/bash

# make sure all the files we mount into the container exist
for i in .bash_eternal_history .bashrc_dev_container .inputrc .gitconfig; do
    if [ ! -f $HOME/$i ] ; then
        touch $HOME/$i;
    fi
done

echo "devcontainerID ${1}"
